import re
from playwright.sync_api import sync_playwright


def run(playwright):
    # slow_mo=500: chèn delay 500ms giữa mỗi action để quan sát rõ & chờ UI/data load kịp
    browser = playwright.chromium.launch(headless=False, slow_mo=500)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://localhost:3000/")
    page.get_by_role("banner").get_by_role("button", name="Đăng nhập").click()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("hbhuyhoang04@gmail.com")
    page.get_by_role("textbox", name="Email").press("Tab")
    page.get_by_role("textbox", name="Mật khẩu").fill("123456")
    page.get_by_role("button", name="Đăng nhập").click()
    page.get_by_role("button", name="Gửi yêu cầu tham gia").click()
    page.get_by_role("textbox", name="Vui lòng nêu rõ lý do bạn muố").click()
    page.get_by_role("textbox", name="Vui lòng nêu rõ lý do bạn muố").fill("1. Lý do gia nhập:\nEm muốn tìm một sân chơi giải trí lành mạnh để cân bằng lại áp lực học tập. Boardgame không chỉ là trò chơi mà còn là cách tuyệt vời để rèn luyện tư duy chiến thuật và khả năng thương thuyết.\n2. Kỹ năng bản thân:\nHoạt náo & Dẫn dắt: Có khả năng giải thích luật chơi một cách dễ hiểu, hài hước cho người mới (Newbie).\nTư duy chiến thuật: Nắm bắt nhanh luật chơi, có khả năng phân tích tình huống và đưa ra quyết định nhanh dưới áp lực thời gian.\n")
    page.get_by_role("button", name="Gửi yêu cầu", exact=True).click()
    page.get_by_role("button", name="🚪 Đăng xuất").click()
    page.get_by_role("banner").get_by_role("button", name="Đăng nhập").click()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("setassouji2004@gmail.com")
    page.get_by_role("textbox", name="Mật khẩu").click()
    page.get_by_role("textbox", name="Mật khẩu").fill("123456")
    page.get_by_role("button", name="Đăng nhập").click()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").press("ArrowLeft")
    page.get_by_role("textbox", name="Email").fill("setasouji2004@gmail.com")
    page.get_by_role("button", name="Đăng nhập").click()
    page.get_by_role("button", name="📋 Duyệt yêu cầu").click()
    page.get_by_role("button", name="✅ Chấp nhận").click()
    page.get_by_role("button", name="✓ Xác nhận đã thu phí").click()
    page.get_by_role("button", name="👥 Quản lý thành viên").click()
    page.get_by_role("button", name="🚪 Đăng xuất").click()
    page.get_by_role("banner").get_by_role("button", name="Đăng nhập").click()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("hbhuyhoang04@gmail.com")
    page.get_by_role("textbox", name="Mật khẩu").click()
    page.get_by_role("textbox", name="Mật khẩu").fill("123456")
    page.get_by_role("button", name="Đăng nhập").click()
    page.get_by_role("button", name="🤝 CLB đã tham gia").click()

    # ---------------------
    context.close()
    browser.close()


def test_main_1():
    with sync_playwright() as p:
        run(p)
